### ISSUE TITLE
Installation/configuration issues

### ISSUE THREAD

**Issue by ibusko** [spacetelescope/specview#25]
Some initial findings: 
- installing on a Mac (10.8.5) with Ureka 1.4.1.2:
  - Ureka has outdated astropy (0.3) and outdated numpy (1.8).
  - Ureka has outdated scipy (0.14; specview requires 0.15)
  - Ureka has no PyQt4, Qt, and sip installed. Must do by hand.

**Comment by perrygreenfield** [comment]
yeah, you aren't using the right ureka. Try the one for ssbdev

**Comment by ibusko** [comment]
Indeed, ssbdev has updated versions. It still lacks sip, Qt, and PyQt4 though.

**Comment by perrygreenfield** [comment]
let me ask Christine about that

**Comment by ibusko** [comment]
After a many maneuvering, I was finally able to install everything using ssbdev and run specview! Looks like something went bonkers when first building PyQt4 and that caused all kinds of crazy errors. By whipping out clean all my installations and restarting from scratch, it seems to have worked.

This was on my Mac desktop, which runs 10.8.5. Now, on my brand new laptop which runs 10.10.1, the ssbdev installer fails with an "Installation failed" error. 

When we have this figured out, it would be nice to have someone with nothing installed on his/hers machine to give it a try and see what happens. The sip/Qt/PyQt4 installation is a bit involved anyway; it would be great if we can provide these packages as part of ssbdev/Ureka.

**Comment by ibusko** [comment]
For specview support, we should have pyqtgraph included in Ureka as well.

**Comment by ibusko** [comment]
So, summarizing, the installation steps that worked on my OSX 10.8 machine are:
- installl Qt from the .dmg installer. This will put Qt into one of the default /Library/Frameworks places. 
- then install SSBDEV using instructions from this page: http://ssb.stsci.edu/install_ssb_software_yourself.shtml . The self-updating installation available for STScI local machines somehow didn't work for me.
- make sure you are using the SSBDEV virtualenv (run 'ur_setup - ssbdev')
- locate the version of 'qmake' that resulted from the previous installation of Qt. It should be in /usr/bin/qmake or /usr/local/bin/qmake. Make sure it's named qmake-4.8, as in:
  
  lrwxr-xr-x  1 wheel  9 Feb 27 12:28 /usr/bin/qmake@ -> qmake-4.8
- install Cython by running 'python setup.py install' on its installation directory.
- install sip and PyQt4. Both require that you run three commands from their root directory:
  - python configure.py --qmake /usr/bin/qmake
  - make
  - make install

Note that you _must_ provide the correct qmake executable.
- install pyqtgraph by running 'python setup.py install' on its installation directory.

On a OS 10.10 (Yosemite) machine, the PyQt 'make' is still generating a C compilation error. This must be related somehow to Xcode.

**Comment by stscieisenhamer** [comment]
This would be consistent with how Qt/PyQt needs to be installed in general.

The main issue is that whatever version of python one wants to use, it either has to be the active one or explicitly specified using the --python option for the make of both sip and pyqt.

There are shell scripts that allow one to soft link the pyqt libraries into arbitrary python frameworks from a base python installation. This makes using virtualenv much easier than having to do a complete re-install of pyqt for each new virtualenv, or other python systems such as ssbdev.

**Comment by ibusko** [comment]
Xcode issue: the compilation error in the Yosemite machine could indeed be due to Xcode. In that machine I have Xcode 6.1.1, while in the desktop machine where the compilation does succeed, I have Xcode 4.5.1. Just found that Xcode 4.5.1 doesn't install under Yosemite …….. $%^%!!

**Comment by ibusko** [comment]
Solution for Yosemite: use miniconda. That way, binaries are downloaded and installed directly, bypassing the need to build. Thus is probably the way to go regardless of which OS is being used.
- download the miniconda script from here: http://conda.pydata.org/miniconda.html
- run the script: sh Miniconda…….sh
- read and accept the license
- by default, it will install miniconda in your home directory. You can re-define it of course.
- it edits the .bash profile to prepend the path to miniconda into your PATH. You might have to do it yourself if you have customized dot files, or do not use bash, or whatever. Just make sure that in the end you have the path to miniconda at the start of your PATH. And remove from PATH anything that may lead to older/undesired versions of stuff like numpy, astropy, etc.
- then use miniconda to install the desired packages:
  - conda install numpy
  - conda install pyqt
  - conda install astropy
- conda won't install pyqtgraph; for that use 'pip install pyqtgraph'

**Comment by ibusko** [comment]
This is very old and solved by now.

Closing.
